apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airlineprediction-sa-admin-stage
  namespace: airlineprediction-generator-staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: airlineprediction-sa
  namespace: ably77-cicd-environment
